// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    $(".thing-made").addClass("grid-12");
    $(".thing-made .picture").addClass("grid-4");
    return $(".thing-made .description").addClass("grid-8");
  });

}).call(this);
